"use server"
import { revalidatePath } from "next/cache"
import { requireReauth } from "@/lib/auth/guards"
import { getSessionUser } from "@/lib/auth/session"
import { getPool,sql } from "@/lib/db"
import { getReviewableOrder } from "@/lib/repositories/public"
export async function getReviewEligibility(serviceId:string):Promise<boolean>{const user=await getSessionUser();if(!user)return false;return Boolean(await getReviewableOrder(serviceId,user.id))}
export async function addReview(formData:FormData){const user=await requireReauth(String(formData.get("password")??"")),serviceId=String(formData.get("serviceId")??""),rating=Number(formData.get("rating")),content=String(formData.get("content")??"").trim();if(!serviceId||!Number.isInteger(rating)||rating<1||rating>5||!content||content.length>2000)throw new Error("Reseña inválida");const orderId=await getReviewableOrder(serviceId,user.id);if(!orderId)throw new Error("Necesitas completar un pedido de este servicio antes de dejar una reseña");const pool=await getPool();await pool.request().input("order",sql.UniqueIdentifier,orderId).input("service",sql.UniqueIdentifier,serviceId).input("user",sql.UniqueIdentifier,user.id).input("rating",sql.TinyInt,rating).input("content",sql.NVarChar(2000),content).query(`INSERT dbo.reviews(order_id,service_id,user_id,rating,content) VALUES(@order,@service,@user,@rating,@content)`);revalidatePath(`/services/${serviceId}`)}
export async function editReview(reviewId:string,formData:FormData){const user=await requireReauth(String(formData.get("password")??"")),rating=Number(formData.get("rating")),content=String(formData.get("content")??"").trim();if(!reviewId||!Number.isInteger(rating)||rating<1||rating>5||!content||content.length>2000)throw new Error("Reseña inválida");const pool=await getPool(),r=await pool.request().input("id",sql.UniqueIdentifier,reviewId).input("user",sql.UniqueIdentifier,user.id).input("rating",sql.TinyInt,rating).input("content",sql.NVarChar(2000),content).query(`UPDATE dbo.reviews SET rating=@rating,content=@content,updated_at=SYSUTCDATETIME() OUTPUT inserted.service_id WHERE id=@id AND user_id=@user`);if(!r.recordset[0])throw new Error("No puedes editar esta reseña");revalidatePath(`/services/${String(r.recordset[0].service_id)}`)}
export async function replyToReview(reviewId:string,formData:FormData){const user=await requireReauth(String(formData.get("password")??"")),reply=String(formData.get("reply")??"").trim();if(!reviewId||!reply||reply.length>2000)throw new Error("Respuesta inválida");const pool=await getPool(),r=await pool.request().input("id",sql.UniqueIdentifier,reviewId).input("user",sql.UniqueIdentifier,user.id).input("reply",sql.NVarChar(2000),reply).query(`UPDATE r SET r.freelancer_reply=@reply,r.freelancer_reply_at=SYSUTCDATETIME() OUTPUT inserted.service_id FROM dbo.reviews r JOIN dbo.services s ON s.id=r.service_id WHERE r.id=@id AND s.freelancer_id=@user`);if(!r.recordset[0])throw new Error("No puedes responder esta reseña");revalidatePath(`/services/${String(r.recordset[0].service_id)}`)}
