import "server-only"
import { getPool,sql } from "@/lib/db"
import type { Category,Profile,Review,Service,Testimonial } from "@/types"
const iso=(v:unknown)=>v instanceof Date?v.toISOString():String(v), num=(v:unknown)=>Number(v)
function category(r:Record<string,unknown>):Category{return{id:String(r.id),name:String(r.name),slug:String(r.slug),icon:String(r.icon),description:String(r.description),services_count:num(r.services_count),created_at:iso(r.created_at)}}
function service(r:Record<string,unknown>):Service{const imgs=JSON.parse(String(r.image_rows||"[]")),tags=JSON.parse(String(r.tag_rows||"[]"));return{id:String(r.id),title:String(r.title),description:String(r.description),long_description:String(r.long_description),category_id:String(r.category_id),freelancer_id:String(r.freelancer_id),price:num(r.price),delivery_time:String(r.delivery_time),rating:num(r.rating),reviews_count:num(r.reviews_count),sales:num(r.sales),active:Boolean(r.active),created_at:iso(r.created_at),images:imgs.map((x:{image_url:string})=>x.image_url),tags:tags.map((x:{tag:string})=>x.tag),category:{id:String(r.category_id),name:String(r.category_name),slug:String(r.category_slug),icon:String(r.category_icon),description:String(r.category_description),services_count:num(r.category_services_count),created_at:iso(r.category_created_at)},freelancer:r.freelancer_name?{id:String(r.freelancer_id),email:"",name:String(r.freelancer_name),avatar_url:r.freelancer_avatar?String(r.freelancer_avatar):null,role:"freelancer",title:r.freelancer_title?String(r.freelancer_title):null,rating:num(r.freelancer_rating),reviews_count:num(r.freelancer_reviews_count),completed_projects:num(r.freelancer_projects),description:r.freelancer_description?String(r.freelancer_description):null,bio:r.freelancer_bio?String(r.freelancer_bio):null,skills:[],hourly_rate:r.freelancer_rate==null?null:num(r.freelancer_rate),location:r.freelancer_location?String(r.freelancer_location):null,languages:[],verified:Boolean(r.freelancer_verified),created_at:iso(r.freelancer_created_at)}:undefined}}
const SELECT=`SELECT s.*,c.name category_name,c.slug category_slug,c.icon category_icon,c.description category_description,c.services_count category_services_count,c.created_at category_created_at,p.name freelancer_name,p.avatar_url freelancer_avatar,p.title freelancer_title,p.rating freelancer_rating,p.reviews_count freelancer_reviews_count,p.completed_projects freelancer_projects,p.description freelancer_description,p.bio freelancer_bio,p.hourly_rate freelancer_rate,p.location freelancer_location,p.verified freelancer_verified,p.created_at freelancer_created_at,(SELECT image_url FROM dbo.service_images i WHERE i.service_id=s.id ORDER BY sort_order FOR JSON PATH) image_rows,(SELECT tag FROM dbo.service_tags t WHERE t.service_id=s.id FOR JSON PATH) tag_rows FROM dbo.services s JOIN dbo.categories c ON c.id=s.category_id JOIN dbo.profiles p ON p.id=s.freelancer_id`;
export async function getCategories():Promise<Category[]>{return(await(await getPool()).request().query(`SELECT * FROM dbo.categories ORDER BY name`)).recordset.map((r:Record<string,unknown>)=>category(r))}
export async function getCategoryBySlug(slug:string):Promise<Category|null>{const r=await(await getPool()).request().input("slug",sql.VarChar(120),slug).query(`SELECT * FROM dbo.categories WHERE slug=@slug`);return r.recordset[0]?category(r.recordset[0]):null}
export async function getServices(categoryId?:string):Promise<Service[]>{const q=(await getPool()).request();let filter="WHERE s.active=1";if(categoryId){q.input("categoryId",sql.UniqueIdentifier,categoryId);filter+=" AND s.category_id=@categoryId"}return(await q.query(`${SELECT} ${filter} ORDER BY s.created_at DESC`)).recordset.map((r:Record<string,unknown>)=>service(r))}
export async function getServiceById(id:string):Promise<Service|null>{const r=await(await getPool()).request().input("id",sql.UniqueIdentifier,id).query(`${SELECT} WHERE s.id=@id`);return r.recordset[0]?service(r.recordset[0]):null}
export async function getServicesByFreelancer(id:string):Promise<Service[]>{const q=(await getPool()).request().input("id",sql.UniqueIdentifier,id);return(await q.query(`${SELECT} WHERE s.active=1 AND s.freelancer_id=@id ORDER BY s.created_at DESC`)).recordset.map((r:Record<string,unknown>)=>service(r))}
export async function getReviewsByService(id:string):Promise<Review[]>{const r=await(await getPool()).request().input("id",sql.UniqueIdentifier,id).query(`SELECT r.*,p.name user_name,COALESCE(NULLIF(p.avatar_url,''),LEFT(p.name,2)) user_avatar FROM dbo.reviews r JOIN dbo.profiles p ON p.id=r.user_id WHERE r.service_id=@id ORDER BY r.created_at DESC`);return r.recordset.map(x=>({...x,id:String(x.id),service_id:String(x.service_id),user_id:String(x.user_id),created_at:iso(x.created_at),rating:num(x.rating)}))}
export async function getPublicFreelancer(id:string):Promise<Profile|null>{const r=await(await getPool()).request().input("id",sql.UniqueIdentifier,id).query(`SELECT p.*,(SELECT skill FROM dbo.profile_skills WHERE profile_id=p.id FOR JSON PATH) skill_rows,(SELECT language FROM dbo.profile_languages WHERE profile_id=p.id FOR JSON PATH) language_rows FROM dbo.profiles p WHERE p.id=@id AND p.role='freelancer'`);const x=r.recordset[0];if(!x)return null;return{...x,id:String(x.id),email:"",rating:num(x.rating),hourly_rate:x.hourly_rate==null?null:num(x.hourly_rate),created_at:iso(x.created_at),skills:JSON.parse(x.skill_rows||"[]").map((v:{skill:string})=>v.skill),languages:JSON.parse(x.language_rows||"[]").map((v:{language:string})=>v.language)}}
export async function getTestimonials():Promise<Testimonial[]>{return(await(await getPool()).request().query(`SELECT * FROM dbo.testimonials ORDER BY created_at`)).recordset.map((r:Record<string,unknown>)=>({...r,id:String(r.id),name:String(r.name),role:String(r.role),avatar:String(r.avatar),content:String(r.content),rating:num(r.rating),created_at:iso(r.created_at)}))}
export async function getPublicStats(){const r=(await(await getPool()).request().query(`SELECT (SELECT COUNT(*) FROM dbo.[orders] WHERE status='completed') projects,(SELECT COUNT(*) FROM dbo.profiles WHERE role='freelancer') freelancers,(SELECT COALESCE(AVG(CAST(rating AS decimal(5,2))),0) FROM dbo.services WHERE active=1) rating`)).recordset[0];return{projects:num(r.projects),freelancers:num(r.freelancers),rating:num(r.rating)}}
